# Generated by Django 4.2.6 on 2023-10-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_overview', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(to='teaching_overview.course'),
        ),
    ]
