# Generated by Django 4.2.6 on 2023-10-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_overview', '0003_person_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deacription',
            new_name='description',
        ),
    ]
